services:
    sheer.img_to_attach.listener:
        class: sheer\img_to_attach\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@request'
            - '@auth'
            - '@sheer.img_to_attach.helper'
            - '@ext.manager'
        tags:
            - { name: event.listener }
    sheer.img_to_attach.helper:
        class: sheer\img_to_attach\core\helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@request'
            - '@ext.manager'
